### ISSUE TITLE
No module named "celery"

### ISSUE THREAD

**Issue by nottrobin** [canonical-ols/talisker#384]
If I install Talisker, and try to run with gevent, I get a celery error:

``` bash
$ talisker.gunicorn.gevent webapp.app:app --bind 0.0.0.0:8030 --worker-class gevent --name talisker-6fd2e47c12b8 --reload --log-level debug --timeout 9999
2018-12-14 17:10:07.935Z INFO talisker.sentry.TaliskerSentryClient "Raven is not configured (logging is disabled). Please see the documentation for more information."
2018-12-14 17:10:07.939Z INFO talisker.statsd "configuring statsd DummyClient"
Traceback (most recent call last):
  File "/usr/local/bin/talisker.gunicorn.gevent", line 11, in <module>
    sys.exit(run_gunicorn_gevent())
  File "/usr/local/lib/python3.6/dist-packages/talisker/__init__.py", line 266, in run_gunicorn_gevent
    run_gunicorn()
  File "/usr/local/lib/python3.6/dist-packages/talisker/__init__.py", line 239, in run_gunicorn
    import talisker.celery
  File "/usr/local/lib/python3.6/dist-packages/talisker/celery.py", line 35, in <module>
    from raven.contrib.celery import SentryCeleryHandler
  File "/usr/local/lib/python3.6/dist-packages/raven/contrib/celery/__init__.py", line 12, in <module>
    from celery.exceptions import SoftTimeLimitExceeded
ModuleNotFoundError: No module named 'celery'
```

**Comment by bloodearnest** [comment]
This seems to be a recent regression introduced by a refactor. Will fix ASAP.
