### ISSUE TITLE
Talisker incompatible with Flask 1.1.1 (No module named 'werkzeug.wrappers.json')

### ISSUE THREAD

**Issue by nottrobin** [canonical-ols/talisker#475]
Although Talisker [claims](https://github.com/canonical-ols/talisker/blob/master/setup.py#L155) to support `flask>=0.11,<1.2`, flask 1.1.1 requires "Werkzeug>=0.15", but Talisker requires "Werkzeug<0.15,>=0.10.4".

If I install Flask first then when I install Werkzeug I see:

> talisker 0.14.3 has requirement Werkzeug<0.15,>=0.10.4, but you'll have werkzeug 0.15.5 which is incompatible.

But everything seems to work okay.

If I install Talisker first, then when I install Flask 1.1.1 I see:

> flask 1.1.1 has requirement Werkzeug>=0.15, but you'll have werkzeug 0.14.1 which is incompatible.

And then I get the following error:

```
2019-08-02 13:54:25.614Z ERROR gunicorn.error "Exception in worker process"                                                                                                                                        
Traceback (most recent call last):                                                                                                                                                                                 
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/arbiter.py", line 583, in spawn_worker                                                                                                                     
    worker.init_process()                                                                                                                                                                                          
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/workers/base.py", line 129, in init_process                                                                                                                
    self.load_wsgi()                                                                                                                                                                                               
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/workers/base.py", line 138, in load_wsgi                                                                                                                   
    self.wsgi = self.app.wsgi()                                                                                                                                                                                    
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/app/base.py", line 67, in wsgi                                                                                                                             
    self.callable = self.load()                                                                                                                                                                                    
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load                                                                                                                          
    return self.load_wsgiapp()                                                                                                                                                                                     
  File "/usr/local/lib/python3.6/dist-packages/talisker/gunicorn.py", line 146, in load_wsgiapp                                                                                                                    
    app = super(TaliskerApplication, self).load_wsgiapp()                                                                                                                                                          
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp                                                                                                                  
    return util.import_app(self.app_uri)                                                                                                                                                                           
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/util.py", line 350, in import_app                                                                                                                          
    __import__(module)                                                                                                                                                                                             
  File "/home/robin/Projects/jp.ubuntu.com/webapp/app.py", line 6, in <module>                                                                                                                                     
    import flask                                                                                                                                                                                                   
  File "/usr/local/lib/python3.6/dist-packages/flask/__init__.py", line 21, in <module>                                                                                                                            
    from .app import Flask                                                                         
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 69, in <module>                                                                                     
    from .wrappers import Request                                                                                     
  File "/usr/local/lib/python3.6/dist-packages/flask/wrappers.py", line 14, in <module>                                                                       
    from werkzeug.wrappers.json import JSONMixin as _JSONMixin                               
ModuleNotFoundError: No module named 'werkzeug.wrappers.json'; 'werkzeug.wrappers' is not a package                                                             
```

**Comment by bloodearnest** [comment]
This is fixed in talisker, 0.15.0, which explicitly supports werkzeug 0.15
