### ISSUE TITLE
IPDB doens't work with Talisker

### ISSUE THREAD

**Issue by jkfran** [canonical-ols/talisker#530]
Hello,

We are using the Python package [ipdb](https://pypi.org/project/ipdb/) to debug locally in our websites. Since the last version of Talisker was published we are not able to debug using ipdb, this is the traceback error:

<details>
  <summary>Traceback error</summary>
  
  ```
Traceback (most recent call last):
  File "/home/fran/Workspace/charmhub.io/.venv/lib/python3.6/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/fran/Workspace/charmhub.io/.venv/lib/python3.6/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/fran/Workspace/charmhub.io/.venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/fran/Workspace/charmhub.io/.venv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/fran/Workspace/charmhub.io/.venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/fran/Workspace/charmhub.io/.venv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/fran/Workspace/charmhub.io/.venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/fran/Workspace/charmhub.io/.venv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/fran/Workspace/charmhub.io/.venv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/fran/Workspace/charmhub.io/webapp/app.py", line 31, in index
    import ipdb
  File "/snap/dotrun/33/lib/python3.6/site-packages/ipdb/__init__.py", line 7, in <module>
    from ipdb.__main__ import set_trace, post_mortem, pm, run             # noqa
  File "/snap/dotrun/33/lib/python3.6/site-packages/ipdb/__main__.py", line 15, in <module>
    from IPython import get_ipython
  File "/snap/dotrun/33/lib/python3.6/site-packages/IPython/__init__.py", line 56, in <module>
    from .terminal.embed import embed
  File "/snap/dotrun/33/lib/python3.6/site-packages/IPython/terminal/embed.py", line 16, in <module>
    from IPython.terminal.interactiveshell import TerminalInteractiveShell
  File "/snap/dotrun/33/lib/python3.6/site-packages/IPython/terminal/interactiveshell.py", line 19, in <module>
    from prompt_toolkit.enums import DEFAULT_BUFFER, EditingMode
  File "/snap/dotrun/33/lib/python3.6/site-packages/prompt_toolkit/__init__.py", line 16, in <module>
    from .application import Application
  File "/snap/dotrun/33/lib/python3.6/site-packages/prompt_toolkit/application/__init__.py", line 1, in <module>
    from .application import Application
  File "/snap/dotrun/33/lib/python3.6/site-packages/prompt_toolkit/application/application.py", line 39, in <module>
    from prompt_toolkit.buffer import Buffer
  File "/snap/dotrun/33/lib/python3.6/site-packages/prompt_toolkit/buffer.py", line 28, in <module>
    from .application.current import get_app
  File "/snap/dotrun/33/lib/python3.6/site-packages/prompt_toolkit/application/current.py", line 70, in <module>
    "_current_app_session", default=AppSession()
TypeError: 'type' object is not subscriptable
  ```
</details>

@nottrobin created the following repo with an example to reproduce the error:
https://github.com/nottrobin/gunicorn-ipdb-error

Thanks!

**Comment by jkfran** [comment]
This a duplicate of https://github.com/canonical-ols/talisker/issues/529

Thanks!

**Comment by nottrobin** [comment]
Sorry, my issue is a duplicate: https://github.com/canonical-ols/talisker/issues/529. I'll close mine.
