### ISSUE TITLE
Crash on startup with `--statsd-*` command line

### ISSUE THREAD

**Issue by maxiberta** [canonical-ols/talisker#67]
Hi! Talisker crashes if Gunicorn's `--statsd-host` or `--statsd-prefix` are set (regardless of `STATSD_DSN` env var being set or not).

```bash
$ talisker django_project.wsgi:application --bind 0.0.0.0:8000 --statsd-host=test:123 --statsd-prefix=test
2017-04-10 14:10:47.196Z INFO talisker.sentry.TaliskerSentryClient "Raven is not configured (logging is disabled). Please see the documentation for more information."
2017-04-10 14:10:47.196Z INFO talisker.statsd "configuring statsd DummyClient"
2017-04-10 14:10:47.244Z INFO talisker.celery "enabled talisker celery signals"
2017-04-10 14:10:47.250Z WARNING talisker.gunicorn "ignoring gunicorn statsd config, as has no effect when using talisker, as it uses STATS_DSN env var" statsd_prefix= statsd_host="('test', 123)"
Traceback (most recent call last):
  File "env/bin/talisker", line 11, in <module>
    sys.exit(run())
  File "env/local/lib/python2.7/site-packages/talisker/gunicorn.py", line 261, in run
    return app.run()
  File "env/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 192, in run
    super(Application, self).run()
  File "env/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "env/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 61, in __init__
    self.setup(app)
  File "env/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 95, in setup
    self.log = self.cfg.logger_class(app.cfg)
  File "env/local/lib/python2.7/site-packages/talisker/gunicorn.py", line 68, in __init__
    super(GunicornLogger, self).__init__(cfg)
  File "env/local/lib/python2.7/site-packages/gunicorn/instrument/statsd.py", line 31, in __init__
    self.prefix = sub(r"^(.+[^.]+)\.*$", "\g<1>.", cfg.statsd_prefix)
  File "env/lib/python2.7/re.py", line 151, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or buffer
```
```
Python 2.7.6
talisker==0.9.1
gunicorn==19.6.0
```

**Comment by maxiberta** [comment]
Fixed by #71.
