### ISSUE TITLE
Type error emiting request status metric

### ISSUE THREAD

**Issue by maxiberta** [canonical-ols/talisker#68]
When running on Python 2, I'm getting a `TypeError` on each request when Gunicorn emits stats.

```python
2017-04-10 14:40:07.928Z ERROR gunicorn.error "Error handling request"
Traceback (most recent call last):
  File "env/local/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 185, in handle_request
    self.log.access(resp, req, environ, request_time)
  File "env/local/lib/python2.7/site-packages/talisker/gunicorn.py", line 126, in access
    self.increment("gunicorn.request.status.%d" % status, 1)
TypeError: %d format: a number is required, not str
```

```
Python 2.7.6
talisker==0.9.1
gunicorn==19.6.0
```

**Comment by maxiberta** [comment]
Fixed by #71.
